//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating_it3
    {
        public int suburb_id { get; set; }
        public string suburb { get; set; }
        public Nullable<int> postcode { get; set; }
        public string distance_to_city_rate { get; set; }
        public Nullable<double> distance_to_city { get; set; }
        public string travel_time_to_city { get; set; }
        public string residential_rate { get; set; }
        public Nullable<double> residential_percent { get; set; }
        public string commercial_rate { get; set; }
        public Nullable<double> commercial_percent { get; set; }
        public Nullable<double> rural_percent { get; set; }
        public Nullable<double> industrial_percent { get; set; }
        public Nullable<double> other_percent { get; set; }
        public string health_services { get; set; }
        public Nullable<double> health_service_count { get; set; }
        public string time_to_hospital_rate { get; set; }
        public string nearest_public_hospital { get; set; }
        public Nullable<double> time_to_hospital { get; set; }
        public Nullable<double> distance_nearest_public_hospital { get; set; }
        public string disability_care_rate { get; set; }
        public Nullable<int> disability_care { get; set; }
        public string aged_care_rate { get; set; }
        public Nullable<int> aged_care { get; set; }
        public string life_style { get; set; }
        public Nullable<double> population_density { get; set; }
        public string population_density_string { get; set; }
        public Nullable<double> age_0_24 { get; set; }
        public Nullable<double> age_25_44 { get; set; }
        public Nullable<double> age_45_64 { get; set; }
        public Nullable<double> age_65_84 { get; set; }
        public Nullable<double> age_85 { get; set; }
        public string time_to_airport_raw { get; set; }
        public string top_country_of_birth_1 { get; set; }
        public string top_country_of_birth_2 { get; set; }
        public string top_country_of_birth_3 { get; set; }
        public string top_country_of_birth_4 { get; set; }
        public string top_country_of_birth_5 { get; set; }
        public string top_language_spoken_1 { get; set; }
        public string top_language_spoken_2 { get; set; }
        public string top_language_spoken_3 { get; set; }
        public string top_language_spoken_4 { get; set; }
        public string top_language_spoken_5 { get; set; }
        public Nullable<double> accident_count { get; set; }
        public string accident_count_rate { get; set; }
        public Nullable<double> fatal_accident_percent { get; set; }
        public Nullable<double> serious_accident_percent { get; set; }
        public Nullable<double> light_accident_percent { get; set; }
        public Nullable<int> offence_count { get; set; }
        public string crime_rate { get; set; }
        public Nullable<double> crime_offence_count { get; set; }
        public Nullable<double> crime_offence_percent { get; set; }
        public string crime_against_person_rate { get; set; }
        public Nullable<double> burglary_offence_count { get; set; }
        public Nullable<double> burglary_offence_percent { get; set; }
        public string burglary_rate { get; set; }
        public Nullable<double> theft_offence_count { get; set; }
        public Nullable<double> theft_offence_percent { get; set; }
        public string theft_rate { get; set; }
        public Nullable<double> expensive_ranking { get; set; }
        public string buy_house_3br_string { get; set; }
        public string buy_unit_2br_string { get; set; }
        public string avg_house_price_3br { get; set; }
        public string avg_unit_price_2br { get; set; }
        public Nullable<int> Public_Transport_Freq { get; set; }
        public Nullable<double> nursery_shops { get; set; }
        public Nullable<double> cafes_count { get; set; }
        public Nullable<double> dining_count { get; set; }
        public Nullable<double> bar_count { get; set; }
        public Nullable<double> golf_count { get; set; }
        public string nearest_fishspot { get; set; }
        public Nullable<double> distance_to_fishspot { get; set; }
    }
}
