//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating_it1
    {
        public int suburb_id { get; set; }
        public string community_name { get; set; }
        public string distance_to_city { get; set; }
        public string residential { get; set; }
        public string health_services { get; set; }
        public string disability_care { get; set; }
        public string aged_care { get; set; }
        public string time_to_hospital { get; set; }
        public string top_country_of_birth_1 { get; set; }
        public string top_country_of_birth_2 { get; set; }
        public string top_country_of_birth_3 { get; set; }
        public string top_country_of_birth_4 { get; set; }
        public string top_country_of_birth_5 { get; set; }
    }
}
