//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectPlace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ResultEntities : DbContext
    {
        public ResultEntities()
            : base("name=ResultEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rating_it1> rating_it1 { get; set; }
    
        public virtual ObjectResult<rating_it1> GetPreferenceResult(string distance_to_city, string residential, string top_country_of_birth, string health_services, string disability_care, string aged_care, string time_to_hospital)
        {
            var distance_to_cityParameter = distance_to_city != null ?
                new ObjectParameter("distance_to_city", distance_to_city) :
                new ObjectParameter("distance_to_city", typeof(string));
    
            var residentialParameter = residential != null ?
                new ObjectParameter("residential", residential) :
                new ObjectParameter("residential", typeof(string));
    
            var top_country_of_birthParameter = top_country_of_birth != null ?
                new ObjectParameter("top_country_of_birth", top_country_of_birth) :
                new ObjectParameter("top_country_of_birth", typeof(string));
    
            var health_servicesParameter = health_services != null ?
                new ObjectParameter("health_services", health_services) :
                new ObjectParameter("health_services", typeof(string));
    
            var disability_careParameter = disability_care != null ?
                new ObjectParameter("disability_care", disability_care) :
                new ObjectParameter("disability_care", typeof(string));
    
            var aged_careParameter = aged_care != null ?
                new ObjectParameter("aged_care", aged_care) :
                new ObjectParameter("aged_care", typeof(string));
    
            var time_to_hospitalParameter = time_to_hospital != null ?
                new ObjectParameter("time_to_hospital", time_to_hospital) :
                new ObjectParameter("time_to_hospital", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rating_it1>("GetPreferenceResult", distance_to_cityParameter, residentialParameter, top_country_of_birthParameter, health_servicesParameter, disability_careParameter, aged_careParameter, time_to_hospitalParameter);
        }
    
        public virtual ObjectResult<rating_it1> GetPreferenceResult(string distance_to_city, string residential, string top_country_of_birth, string health_services, string disability_care, string aged_care, string time_to_hospital, MergeOption mergeOption)
        {
            var distance_to_cityParameter = distance_to_city != null ?
                new ObjectParameter("distance_to_city", distance_to_city) :
                new ObjectParameter("distance_to_city", typeof(string));
    
            var residentialParameter = residential != null ?
                new ObjectParameter("residential", residential) :
                new ObjectParameter("residential", typeof(string));
    
            var top_country_of_birthParameter = top_country_of_birth != null ?
                new ObjectParameter("top_country_of_birth", top_country_of_birth) :
                new ObjectParameter("top_country_of_birth", typeof(string));
    
            var health_servicesParameter = health_services != null ?
                new ObjectParameter("health_services", health_services) :
                new ObjectParameter("health_services", typeof(string));
    
            var disability_careParameter = disability_care != null ?
                new ObjectParameter("disability_care", disability_care) :
                new ObjectParameter("disability_care", typeof(string));
    
            var aged_careParameter = aged_care != null ?
                new ObjectParameter("aged_care", aged_care) :
                new ObjectParameter("aged_care", typeof(string));
    
            var time_to_hospitalParameter = time_to_hospital != null ?
                new ObjectParameter("time_to_hospital", time_to_hospital) :
                new ObjectParameter("time_to_hospital", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rating_it1>("GetPreferenceResult", mergeOption, distance_to_cityParameter, residentialParameter, top_country_of_birthParameter, health_servicesParameter, disability_careParameter, aged_careParameter, time_to_hospitalParameter);
        }
    }
}
